# Spring properties
spring:
  application:
     name: Transactions-Service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# HTTP Server
server:
  port: 8081